[taux_incidence]
dataset = ""
res_id_fra = "taux_fra.csv"
res_id_reg = "taux_reg.csv"
res_id_dep = "taux_dep.csv"
trendType = "normal"
nom = "Taux d'incidence"
unite = "nombre de cas par semaine pour 100 000 habitants"
unite_short = ""

[taux_positivite]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id_fra = "taux_fra.csv"
res_id_reg = "taux_reg.csv"
res_id_dep = "taux_dep.csv"
trendType = "normal"
nom = "Taux de positivité"
unite = "% de cas positifs"
unite_short = "%"

[hospitalisations]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese.csv"
trendType = "normal"
nom = "Nombre de personnes hospitalisées"
unite = "personnes hospitalisées"
unite_short = ""

[hospitalisations_moyenne_quotidienne]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese.csv"
trendType = "normal"
nom = "Nombre moyen de nouvelles hospitalisations quotidiennes"
unite = "nouvelles personnes hospitalisées"
unite_short = ""

[retour_a_domicile]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese.csv"
trendType = "normal"
nom = "Nombre de retours à domicile"
unite = "personnes"
unite_short = ""

[retour_a_domicile_moyenne_quotidienne]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese.csv"
trendType = "normal"
nom = "Nombre moyen de nouveaux retours à domicile quotidiens"
unite = "nouvelles personnes retournées à domicile"
unite_short = ""

[soins_critiques]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese.csv"
trendType = "normal"
nom = "Nombre de personnes en soins critiques "
unite = "personnes en soins critiques"
unite_short = ""

[soins_critiques_moyenne_quotidienne]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese.csv"
trendType = "normal"
nom = "Nombre moyen de nouvelles entrées en soins critiques quotidiennes"
unite = "nouvelles entrées en soins critiques"
unite_short = ""

[deces]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese.csv"
trendType = "normal"
nom = "Décès hospitaliers"
unite = "décès hospitaliers"
unite_short = ""

[deces_moyenne_quotidienne]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese.csv"
trendType = "normal"
nom = "Nombre moyen de décès quotidiens à l'hôpital"
unite = "décès hospitaliers"
unite_short = ""

[deces_total]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese_fra.csv"
trendType = "normal"
nom = "Nombre total des décès à l'hôpital et en ESMS dont EPHAD"
unite = "décès"
unite_short = ""

[vaccins_premiere_dose]
dataset = "donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19-1"
res_id = "vaccin.csv"
trendType = "abnormal"
nom = "Nombre de personnes ayant reçu au moins une dose"
unite = "personnes ayant reçues au moins une dose de vaccin"
unite_short = ""

[vaccins_vaccines]
dataset = "donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19-1"
res_id = "vaccin.csv"
trendType = "abnormal"
nom = "Nombre de personnes complètement vaccinées"
unite = "personnes complètement vaccinées"
unite_short = ""

[vaccins_premiere_dose_moyenne_quotidienne]
dataset = "donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19-1"
res_id = "vaccin.csv"
trendType = "abnormal"
nom = "Nombre quotidien de personnes ayant reçu au moins une dose"
unite = "personnes ayant reçues au moins une dose de vaccin"
unite_short = ""

[vaccins_vaccines_moyenne_quotidienne]
dataset = "donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19-1"
res_id = "vaccin.csv"
trendType = "abnormal"
nom = "Nombre quotidien de personnes complètement vaccinées"
unite = "personnes complètement vaccinées"
unite_short = ""

[cas_positifs]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id = "synthese.csv"
trendType = "normal"
nom = "Nombre moyen de nouveaux cas confirmés quotidiens"
unite = "cas positifs"
unite_short = ""

[facteur_reproduction]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id_fra = "synthese_fra.csv"
res_id_reg = "synthese.csv"
res_id_dep = "synthese.csv"
trendType = "normal"
nom = "Taux de reproduction effectif"
unite = "R"
unite_short = ""

[taux_occupation]
dataset = "synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19"
res_id_fra = "synthese_fra.csv"
res_id_reg = "synthese.csv"
res_id_dep = "synthese.csv"
trendType = "normal"
nom = "Taux d'occupation"
unite = "% d'occupation"
unite_short = "%"

[vaccins_vaccines_couv_majeurs]
dataset = "donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19-1"
res_id_fra = "vaccin_couv_fra.csv"
res_id_reg = "vaccin_couv_reg.csv"
res_id_dep = "vaccin_couv_dep.csv"
pop_id_fra = "pop_age_fra.csv"
pop_id_reg = "pop_age_reg.csv"
pop_id_dep = "pop_age_dep.csv"
trendType = "abnormal"
nom = "Part de la population majeure complètement vaccinée "
unite = "% de la population majeure complètement vaccinée "
unite_short = "%"

[vaccins_vaccines_couv_ado_majeurs]
dataset = "donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19-1"
res_id_fra = "vaccin_couv_fra.csv"
res_id_reg = "vaccin_couv_reg.csv"
res_id_dep = "vaccin_couv_dep.csv"
pop_id_fra = "pop_age_fra.csv"
pop_id_reg = "pop_age_reg.csv"
pop_id_dep = "pop_age_dep.csv"
trendType = "abnormal"
nom = "Part de la population âgée de plus de 12 ans complètement vaccinée "
unite = "% de la population âgée de plus de 12 ans complètement vaccinée "
unite_short = "%"

[prop_variant_A]
dataset = "donnees-de-laboratoires-pour-le-depistage-indicateurs-sur-les-mutations"
res_id_fra = "prop_variants_fra.csv"
res_id_reg = "prop_variants_reg.csv"
res_id_dep = "prop_variants_dep.csv"
trendType = "normal"
nom = "Mutation E484K (dont variants Beta, Gamma)"
unite = "% Mutation E484K"
unite_short = "%"

[prop_variant_B]
dataset = "donnees-de-laboratoires-pour-le-depistage-indicateurs-sur-les-mutations"
res_id_fra = "prop_variants_fra.csv"
res_id_reg = "prop_variants_reg.csv"
res_id_dep = "prop_variants_dep.csv"
trendType = "normal"
nom = "Mutation E484Q"
unite = "% Mutation E484Q"
unite_short = "%"

[prop_variant_C]
dataset = "donnees-de-laboratoires-pour-le-depistage-indicateurs-sur-les-mutations"
res_id_fra = "prop_variants_fra.csv"
res_id_reg = "prop_variants_reg.csv"
res_id_dep = "prop_variants_dep.csv"
trendType = "normal"
nom = "Mutation L452R (dont variant Delta)"
unite = "% Mutation L452R"
unite_short = "%"

[pos_test_vacsi]
dataset = "résultats nationaux issus des appariements entre SI-VIC, SI-DEP et VAC-SI"
res_id_fra = "vacsi_non_vacsi_nat.csv"
res_id_reg = "vacsi_non_vacsi_reg.csv"
trendType = "normal"
nom = "Nombre de tests positifs chez les personnes vaccinées"
unite = "tests positifs pour 100 000 personnes vaccinées"
unite_short=""

[pos_test_non_vacsi]
dataset = "résultats nationaux issus des appariements entre SI-VIC, SI-DEP et VAC-SI"
res_id_fra = "vacsi_non_vacsi_nat.csv"
res_id_reg = "vacsi_non_vacsi_reg.csv"
trendType = "normal"
nom = "Nombre de tests positifs chez les personnes non vaccinées"
unite = "tests positifs pour 100 000 personnes non vaccinées"
unite_short=""

[sc_vacsi]
dataset = "résultats nationaux issus des appariements entre SI-VIC, SI-DEP et VAC-SI"
res_id_fra = "vacsi_non_vacsi_nat.csv"
res_id_reg = "vacsi_non_vacsi_reg.csv"
trendType = "normal"
nom = "Nombre d'entrées en soins critiques chez les personnes vaccinées"
unite = "entrées en soins critiques pour 1 million de personnes vaccinées"
unite_short=""

[sc_non_vacsi]
dataset = "résultats nationaux issus des appariements entre SI-VIC, SI-DEP et VAC-SI"
res_id_fra = "vacsi_non_vacsi_nat.csv"
res_id_reg = "vacsi_non_vacsi_reg.csv"
trendType = "normal"
nom = "Nombre d'entrées en soins critiques chez les personnes non vaccinées"
unite = "entrées en soins critiques pour 1 million de personnes non vaccinées"
unite_short=""

[nb_classes_fermees]
dataset = "fr-en-situation_nationale_covid"
res_id = "scolaire_nat.csv"
protocole_id = "historique_protocole_sanitaire.csv"
trendType = "normal"
nom = "Nombre de classes fermées"
unite = "classes fermées"
unite_short = ""

[taux_classes_fermees]
dataset = "fr-en-situation_nationale_covid"
res_id = "scolaire_nat.csv"
protocole_id = "historique_protocole_sanitaire.csv"
trendType = "normal"
nom = "Taux de classes fermées"
unite = "% classes fermées"
unite_short = "%"

[nb_structures_fermees]
dataset = "fr-en-situation_nationale_covid"
res_id = "scolaire_nat.csv"
protocole_id = "historique_protocole_sanitaire.csv"
trendType = "normal"
nom = "Nombre de structures scolaires fermées"
unite = "structures scolaires fermées"
unite_short = ""

[taux_structures_fermees]
dataset = "fr-en-situation_nationale_covid"
res_id = "scolaire_nat.csv"
protocole_id = "historique_protocole_sanitaire.csv"
trendType = "normal"
nom = "Taux de structures scolaires fermées"
unite = "% structures scolaires fermées"
unite_short = "%"

[nb_college_lycee_vaccin]
dataset = "fr-en-situation_nationale_covid"
res_id = "scolaire_nat.csv"
protocole_id = "historique_protocole_sanitaire.csv"
trendType = "abnormal"
nom = "Nombre de collèges et lycées proposant un parcours vaccinal aux élèves"
unite = "collèges et lycées proposant un parcours vaccinal aux élèves"
unite_short = ""
constante_label = "Nombre total de collèges et lycées"
constante_value = 11400

[vaccins_rappel]
dataset = "donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19-1"
res_id_fra = "vaccin_rappel_nat.csv"
res_id_reg = "vaccin_rappel_reg.csv"
res_id_dep = "vaccin_rappel_dep.csv"
trendType = "abnormal"
nom = "Nombre de personnes ayant reçu une dose de rappel"
unite = "personnes ayant reçu une dose de rappel"
unite_short = ""

[vaccins_rappel_moyenne_quotidienne]
dataset = "donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19-1"
res_id_fra = "vaccin_rappel_nat.csv"
res_id_reg = "vaccin_rappel_reg.csv"
res_id_dep = "vaccin_rappel_dep.csv"
trendType = "abnormal"
nom = "Nombre quotidien de personnes ayant reçu une dose de rappel"
unite = "personnes ayant reçu une dose de rappel"
unite_short = ""
